### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by svenefftinge** [32leaves/ruruku#34]
For claimed, items it would great to have a direct 'Passed', 'Failed' button.
Also, maybe you could put the form below the line to keep the context.
Claimed tests would automatically be opened.

**Comment by 32leaves** [comment]
I agree - at the moment the passed/failed buttons are yet another click away when they would not have to be.

I' not sure I understand _claimed tests would automatically be opened_. Would they open on the side the moment a user claims them?
